# ==============================================================================
# Caligo Exploration Suite - Dry Run with Visualization Test Configuration
# ==============================================================================
# Minimal configuration for testing full pipeline including vis/tables

output:
  base_dir: "exploration_results"
  campaign_name: "dry_run_with_viz"
  timestamped: true

# Phase 1: Minimal LHS warmup (10 feasible samples target)
phase1:
  num_samples: 10
  batch_size: 5
  checkpoint_interval: 1
  strategy_ratio: 0.5

# Phase 2: Surrogate training
phase2:
  gp:
    kernel_type: "matern52"
    n_restarts_optimizer: 2
    normalize_y: true
  
  validation_split: 0.2

# Phase 3: Minimal active learning (3 iterations)
phase3:
  num_iterations: 3
  batch_size: 2
  retrain_interval: 2
  checkpoint_interval: 1
  
  acquisition:
    type: "straddle"
    kappa: 1.96

# Parameter bounds (using default ranges)
bounds:
  storage_noise_r:
    min: 0.0
    max: 1.0
  
  storage_rate_nu:
    min: 0.001
    max: 1.0
  
  wait_time_ns:
    min_log: 5.0
    max_log: 9.0
  
  channel_fidelity:
    min: 0.501
    max: 1.0
  
  detection_efficiency:
    min_log: -3.0
    max_log: 0.0
  
  detector_error:
    min: 0.0
    max: 0.1
  
  dark_count_prob:
    min_log: -8.0
    max_log: -3.0
  
  num_pairs:
    min_log: 4.0
    max_log: 6.0

# Execution settings
execution:
  num_workers: 4
  timeout_seconds: 120.0
  random_seed: 42
  log_level: "INFO"

# Visualization ENABLED for testing
visualization:
  enabled: true

# Tables ENABLED for testing
tables:
  enabled: true
  formats:
    - csv
    - markdown
  qber_levels:
    - 0.01
    - 0.03
    - 0.05
    - 0.08
    - 0.10
  storage_noise_levels:
    - 0.90
    - 0.85
    - 0.80
    - 0.75
